# Generated by Django 3.1.4 on 2021-01-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='value',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='run',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='return_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='stderr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='stdout',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='stop',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='amqp_connection',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='portal.amqpconnection'),
        ),
        migrations.AlterField(
            model_name='task',
            name='command_line',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='task',
            name='queue_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
