# Generated by Django 3.1.4 on 2021-01-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210107_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='return_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='amqp_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portal.amqpconnection'),
        ),
    ]
