# Generated by Django 3.1.4 on 2021-01-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210107_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
