# Generated by Django 3.1.4 on 2021-01-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210107_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaemonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('message', models.CharField(max_length=256)),
                ('level_name', models.CharField(max_length=16)),
            ],
        ),
    ]
